// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgrgsczeecjdqezuvlwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtncmdzY3plZWNqZHFlenV2bHd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTU2MTIsImV4cCI6MjA2ODc3MTYxMn0.5_7XvHclhMuJXsCJlFrtc0GW7m0aE_USwS3N90kN9MY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});